// <auto-generated />
using System;
using EnglishCoach.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnglishCoach.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnglishCoachDbContext))]
    [Migration("20260426101147_AddInterviewPractice")]
    partial class AddInterviewPractice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnglishCoach.Domain.Curriculum.Phrase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CommunicationFunction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ContentVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ViMeaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationFunction");

                    b.HasIndex("Level");

                    b.HasIndex("State");

                    b.ToTable("Phrases");
                });

            modelBuilder.Entity("EnglishCoach.Domain.Curriculum.RoleplayScenario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClientPersona")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CommunicationGoal")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ContentVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("MustCoverPoints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassCriteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetPhraseIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WorkplaceContext")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("RoleplayScenarios");
                });

            modelBuilder.Entity("EnglishCoach.Domain.ErrorNotebook.NotebookEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CorrectedExample")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceRefs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExplanationVi")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OriginalExample")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PatternKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RecurrenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("LearnerId", "PatternKey")
                        .IsUnique();

                    b.ToTable("NotebookEntries");
                });

            modelBuilder.Entity("EnglishCoach.Domain.Identity.LearnerProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<string>("CurrentEnglishLevel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("current_english_level");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("NativeLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("native_language");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<int>("TargetTimelineWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("target_timeline_weeks");

                    b.Property<string>("TargetUseCase")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("target_use_case");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.HasKey("UserId");

                    b.ToTable("learner_profiles", (string)null);
                });

            modelBuilder.Entity("EnglishCoach.Domain.InterviewPractice.InterviewProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CvAnalysis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("CvText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.ToTable("InterviewProfiles");
                });

            modelBuilder.Entity("EnglishCoach.Domain.InterviewPractice.InterviewSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InterviewPlan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("InterviewProfileId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("JdAnalysis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("JdText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PlannedQuestionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InterviewProfileId");

                    b.HasIndex("LearnerId");

                    b.ToTable("InterviewSessions");
                });

            modelBuilder.Entity("EnglishCoach.Domain.InterviewPractice.InterviewTurn", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("InterviewTurns");
                });

            modelBuilder.Entity("EnglishCoach.Domain.Progress.ReadinessSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ComponentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("FormulaVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.ToTable("ReadinessSnapshots", (string)null);
                });

            modelBuilder.Entity("EnglishCoach.Domain.Review.ReviewAttempt", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<long>("CompletedAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("NextDueAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("next_due_at_utc");

                    b.Property<int>("NextRepetitionCount")
                        .HasColumnType("integer")
                        .HasColumnName("next_repetition_count");

                    b.Property<string>("NextState")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("next_state");

                    b.Property<int>("PreviousRepetitionCount")
                        .HasColumnType("integer")
                        .HasColumnName("previous_repetition_count");

                    b.Property<string>("PreviousState")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("previous_state");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quality");

                    b.Property<string>("ReviewItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("review_item_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewItemId");

                    b.ToTable("review_attempts", (string)null);
                });

            modelBuilder.Entity("EnglishCoach.Domain.Review.ReviewItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplaySubtitle")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("display_subtitle");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("display_text");

                    b.Property<long>("DueAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("due_at_utc");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("item_id");

                    b.Property<long?>("LastCompletedAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("last_completed_at_utc");

                    b.Property<string>("MasteryState")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("mastery_state");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("integer")
                        .HasColumnName("repetition_count");

                    b.Property<string>("ReviewTrack")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("review_track");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId", "ReviewTrack")
                        .IsUnique();

                    b.ToTable("review_items", (string)null);
                });

            modelBuilder.Entity("EnglishCoach.Domain.Roleplay.RoleplaySession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ScenarioContentVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.ToTable("RoleplaySessions");
                });

            modelBuilder.Entity("EnglishCoach.Domain.Roleplay.RoleplayTurn", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("RoleplayTurns");
                });

            modelBuilder.Entity("EnglishCoach.Domain.Speaking.SpeakingAttempt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContentItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedTranscript")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RawTranscript")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("LearnerId");

                    b.ToTable("SpeakingAttempts");
                });

            modelBuilder.Entity("EnglishCoach.Domain.InterviewPractice.InterviewSession", b =>
                {
                    b.OwnsOne("EnglishCoach.Domain.InterviewPractice.InterviewFeedback", "Feedback", b1 =>
                        {
                            b1.Property<string>("InterviewSessionId")
                                .HasColumnType("text");

                            b1.Property<int>("CommunicationScore")
                                .HasColumnType("integer")
                                .HasColumnName("FeedbackCommunicationScore");

                            b1.Property<int>("ConfidenceScore")
                                .HasColumnType("integer")
                                .HasColumnName("FeedbackConfidenceScore");

                            b1.Property<string>("DetailedFeedbackEn")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("FeedbackDetailedEn");

                            b1.Property<string>("DetailedFeedbackVi")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("FeedbackDetailedVi");

                            b1.Property<string>("ImprovementAreas")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FeedbackImprovementAreas");

                            b1.Property<int>("OverallScore")
                                .HasColumnType("integer")
                                .HasColumnName("FeedbackOverallScore");

                            b1.Property<string>("RetryRecommendation")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("FeedbackRetryRecommendation");

                            b1.Property<string>("StrengthAreas")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FeedbackStrengthAreas");

                            b1.Property<string>("SuggestedPhrases")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FeedbackSuggestedPhrases");

                            b1.Property<int>("TechnicalAccuracyScore")
                                .HasColumnType("integer")
                                .HasColumnName("FeedbackTechnicalAccuracyScore");

                            b1.HasKey("InterviewSessionId");

                            b1.ToTable("InterviewSessions");

                            b1.WithOwner()
                                .HasForeignKey("InterviewSessionId");
                        });

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("EnglishCoach.Domain.InterviewPractice.InterviewTurn", b =>
                {
                    b.HasOne("EnglishCoach.Domain.InterviewPractice.InterviewSession", null)
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishCoach.Domain.Review.ReviewAttempt", b =>
                {
                    b.HasOne("EnglishCoach.Domain.Review.ReviewItem", null)
                        .WithMany()
                        .HasForeignKey("ReviewItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishCoach.Domain.Roleplay.RoleplaySession", b =>
                {
                    b.OwnsOne("EnglishCoach.Domain.Roleplay.RoleplaySummary", "Summary", b1 =>
                        {
                            b1.Property<string>("RoleplaySessionId")
                                .HasColumnType("text");

                            b1.Property<string>("ClearPoints")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("SummaryClearPoints");

                            b1.Property<string>("ImprovedAnswer")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("SummaryImprovedAnswer");

                            b1.Property<string>("PhrasesToReview")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("SummaryPhrasesToReview");

                            b1.Property<string>("Result")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("SummaryResult");

                            b1.Property<string>("RetryChallenge")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("SummaryRetryChallenge");

                            b1.Property<string>("TopMistakes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("SummaryTopMistakes");

                            b1.HasKey("RoleplaySessionId");

                            b1.ToTable("RoleplaySessions");

                            b1.WithOwner()
                                .HasForeignKey("RoleplaySessionId");
                        });

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("EnglishCoach.Domain.Roleplay.RoleplayTurn", b =>
                {
                    b.HasOne("EnglishCoach.Domain.Roleplay.RoleplaySession", null)
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishCoach.Domain.Speaking.SpeakingAttempt", b =>
                {
                    b.OwnsOne("EnglishCoach.Domain.Speaking.SpeakingFeedback", "Feedback", b1 =>
                        {
                            b1.Property<string>("SpeakingAttemptId")
                                .HasColumnType("text");

                            b1.Property<string>("ImprovedAnswer")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("FeedbackImprovedAnswer");

                            b1.Property<string>("PhrasesToReview")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("FeedbackPhrasesToReview");

                            b1.Property<string>("RetryPrompt")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("FeedbackRetryPrompt");

                            b1.Property<string>("TopMistakes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("FeedbackTopMistakes");

                            b1.HasKey("SpeakingAttemptId");

                            b1.ToTable("SpeakingAttempts");

                            b1.WithOwner()
                                .HasForeignKey("SpeakingAttemptId");
                        });

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("EnglishCoach.Domain.InterviewPractice.InterviewSession", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("EnglishCoach.Domain.Roleplay.RoleplaySession", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
