// <auto-generated />
using System;
using EnglishCoach.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnglishCoach.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnglishCoachDbContext))]
    partial class EnglishCoachDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnglishCoach.Domain.Identity.LearnerProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<string>("CurrentEnglishLevel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("current_english_level");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("NativeLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("native_language");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<int>("TargetTimelineWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("target_timeline_weeks");

                    b.Property<string>("TargetUseCase")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("target_use_case");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.HasKey("UserId");

                    b.ToTable("learner_profiles", (string)null);
                });

            modelBuilder.Entity("EnglishCoach.Domain.Review.ReviewAttempt", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<long>("CompletedAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("NextDueAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("next_due_at_utc");

                    b.Property<int>("NextRepetitionCount")
                        .HasColumnType("integer")
                        .HasColumnName("next_repetition_count");

                    b.Property<string>("NextState")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("next_state");

                    b.Property<int>("PreviousRepetitionCount")
                        .HasColumnType("integer")
                        .HasColumnName("previous_repetition_count");

                    b.Property<string>("PreviousState")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("previous_state");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quality");

                    b.Property<string>("ReviewItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("review_item_id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewItemId");

                    b.ToTable("review_attempts", (string)null);
                });

            modelBuilder.Entity("EnglishCoach.Domain.Review.ReviewItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplaySubtitle")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("display_subtitle");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("display_text");

                    b.Property<long>("DueAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("due_at_utc");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("item_id");

                    b.Property<long?>("LastCompletedAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("last_completed_at_utc");

                    b.Property<string>("MasteryState")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("mastery_state");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("integer")
                        .HasColumnName("repetition_count");

                    b.Property<string>("ReviewTrack")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("review_track");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId", "ReviewTrack")
                        .IsUnique();

                    b.ToTable("review_items", (string)null);
                });

            modelBuilder.Entity("EnglishCoach.Domain.Review.ReviewAttempt", b =>
                {
                    b.HasOne("EnglishCoach.Domain.Review.ReviewItem", null)
                        .WithMany()
                        .HasForeignKey("ReviewItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
